# Configure rsyslog.conf
---

#- name: Configure /etc/rsyslog.conf
#  lineinfile: dest=/etc/rsyslog.conf regexp="^RULES " insertafter="^#RULES " line="#bash_history logging"
#  lineinfile: dest=/etc/rsyslog.conf regexp="^RULES " insertafter="^#RULES " line="local6.* {{ audit_log_destination }}"
#  lineinfile: dest=/etc/rsyslog.conf regexp="^forwarding " insertbefore="^#forwarding " line="local6.* @{{ logger_ip }}"

#- name: Configure /etc/rsyslog.conf
#  lineinfile:
#      dest: /etc/rsyslog.conf
#      line: "{{ item.line }}"
#  with_items:
#    - { line: "#bash_history logging",  insertafter: "^#mail" }
#    - { line: "local6.* {{ audit_log_destination }}", insertafter: "^#mail" }
#    - { line: "local6.* @{{ logger_ip }}", insertbefore: "^#forwarding" }

- name: Create /etc/rsyslog.conf
  template:
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    restart rsyslog

#- name: Delete /etc/rsyslog.conf
#  file: path=/etc/rsyslog.conf state=absent

#- name: Rename /etc/rsyslog.conf.org
#  shell: mv /etc/rsyslog.conf.org /etc/rsyslog.conf
#  notify:
#    - restart rsyslog

