#Create logrotate.d/* files
---

- name: Create logrotate.d/* files
  template: 
    src=logrotate.j2
    dest=/etc/logrotate.d/{{ item.name }}
    owner=root
    group=root
    mode=0644
  with_items: 
    - "{{ logrotate_apps }}"