#Files
---

- name: Create logrotate.d/* files
  file: 
    src=logrotate.j2
    dest=/etc/logrotate.d/{{ item.name }}
    owner=root
    group=root
    mode=0644
    state=touch
  with_items: 
    - "{{ logrotate_apps }}"

- name: Edit logrotate.d/* files
  blockinfile: 
    dest: /etc/logrotate.d/{{ item.name }}
    block: |
      /var/log/{{ item.name }}.log {
        {{ logrotate_period }}
        compress
        delaycompress 
        missingok
        notifempty
        postrotate
          /etc/init.d/{{ item.name }} reload >/dev/null 2>/dev/null || true
        endscript
      }
  with_items:
    - "{{ logrotate_apps }}"

- name: Edit cron.daily/logrotate
  lineinfile: 
    dest: /etc/cron.daily/logrotate
    regexp: "/etc/logrotate.conf"
    insertafter: "/etc/logrotate.conf"
    line: '>/dev/null 2>&1'

